### ISSUE TITLE
 status

### ISSUE THREAD

**Issue by leobasis** [codywd/NetGUI#47]

**Comment by codywd** [comment]
If you are asking for the status of this application, I am not 100% sure where it is going. I don't have Arch Linux installed anymore, and thus can't test it. I am willing to try and write the Python code based upon issues, but without a way to test it, I am unable to guarantee any kind of stability. I am also willing to provide this code to a new owner.

I feel horrible about this, because I loved this application, but without the time to develop it anymore, or the ability to test it, it is kind of at a stand still.

**Comment by codywd** [comment]
I won't be able to test wireless networks any more, but I will work on all current bug issues and test it in a VM. Hopefully I can get this to version 1.0 and smash any bugs. When I have spare money, I will be purchase a laptop, and place Arch Linux on it once again to work on more wireless features.

**Comment by codywd** [comment]
Further update, I have purchased a new laptop and put Arch back on it, so development is back in full swing. I have fixed all the major bugs stopping  it from working. In addition, I have fixed the GUI freezes that occurred during scans, although it is not included yet (it is in main-new.py, not main.py).

I am working on closing all the issues as quickly as possible, but development revolves around free time after my full time job and full time master's.
